server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${ALLOWED_ORIGIN:http://localhost:4200}"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: payment-service
          uri: "${PAYMENT_SERVICE_URL:http://localhost:8082}"
          predicates:
            - Path=/api/payments/**,/api/bills/**,/api/maintenance-config/**,/api/admin/collections/**
        - id: core-api
          uri: "${CORE_API_URL:http://localhost:8081}"
          predicates:
            - Path=/api/**
